check:
	SKIP_GUEST_BUILD=1 cargo check
	SKIP_GUEST_BUILD=1 cargo check --manifest-path crates/provers/risc0/guest-celestia/Cargo.toml
	SKIP_GUEST_BUILD=1 cargo check --manifest-path crates/provers/risc0/guest-mock/Cargo.toml
	SKIP_GUEST_BUILD=1 cargo check --manifest-path crates/provers/sp1/guest-celestia/Cargo.toml
	SKIP_GUEST_BUILD=1 cargo check --manifest-path crates/provers/sp1/guest-mock/Cargo.toml

lint:
	SKIP_GUEST_BUILD=1 cargo fmt --all -- --check
	SKIP_GUEST_BUILD=1 cargo check
	SKIP_GUEST_BUILD=1 cargo check --features celestia_da --features risc0 --no-default-features
	SKIP_GUEST_BUILD=1 cargo check --features celestia_da --features sp1 --no-default-features
	SKIP_GUEST_BUILD=1 cargo check --features celestia_da --features mock_zkvm --no-default-features
	SKIP_GUEST_BUILD=1 cargo clippy
	SKIP_GUEST_BUILD=1 cargo clippy --features celestia_da --features risc0 --no-default-features
	SKIP_GUEST_BUILD=1 cargo clippy --features celestia_da --features sp1 --no-default-features
	SKIP_GUEST_BUILD=1 cargo clippy --features celestia_da --features mock_zkvm --no-default-features
	zepter
	zepter
	zepter

npm-install:
	cd examples/starter-js && npm install

npm-start:
	@cd examples/starter-js && npm run start

npm-privy-install:
	@cd examples/privy && npm install

install-risc0-toolchain:
	curl -L https://risczero.com/install | bash
	~/.risc0/bin/rzup install cargo-risczero 2.0.2
	~/.risc0/bin/rzup install rust 1.88.0
	~/.risc0/bin/rzup install cpp 2024.1.5
	@echo "Risc0 toolchain version:"
	cargo +risc0 --version


install-sp1-toolchain:
	curl -L https://raw.githubusercontent.com/succinctlabs/sp1/main/sp1up/install | bash
	~/.sp1/bin/sp1up $${GITHUB_TOKEN:+--token "$$GITHUB_TOKEN"} --version 5.0.8 --c-toolchain
	~/.sp1/bin/cargo-prove prove --version
	~/.sp1/bin/cargo-prove prove install-toolchain
	@echo "SP1 toolchain version:"
	rustc +succinct --version

clean: clean-db
	@cargo clean
	@cargo clean --manifest-path crates/provers/risc0/guest-celestia/Cargo.toml
	@cargo clean --manifest-path crates/provers/risc0/guest-mock/Cargo.toml
	@cargo clean --manifest-path crates/provers/sp1/guest-celestia/Cargo.toml
	@cargo clean --manifest-path crates/provers/sp1/guest-mock/Cargo.toml
	rm -rf examples/starter-js/node_modules
	rm -rf examples/privy/node_modules
	rm crates/stf/runtime_call.json
	rm crates/stf/autogenerated.inc.rs

clean-db:
	rm -rf test-data/rollup-starter-data
	rm -rf test-data/rollup-starter-data-celestia
	rm -rf test-data/mock_da.sqlite

# Use `--build-arg BUILD_MODE=release` for release builds
build-docker-mock-da:
	DOCKER_BUILDKIT=1 \
	docker build \
	--ssh default \
	-f ./docker/rollup/Dockerfile.mock \
	-t rollup-starter:debug \
	.

run-docker-mock-da:
	mkdir -p docker/rollup/data
	mkdir -p docker/rollup/data/da
	mkdir -p docker/rollup/data/state
	docker run --rm -it \
			-v $(CURDIR)/docker/rollup/data/da:/mnt/da \
			-v $(CURDIR)/docker/rollup/data/state:/mnt/state \
			-v $(CURDIR)/configs/mock/rollup-dockerized.toml:/app/config/rollup.toml \
			-p 12346:12346 \
			rollup-starter:debug

start-obs:
	./scripts/start_observability.sh

stop-obs:
	./scripts/stop_observability.sh